title: Luqman's website
paginate: 6
theme: charlolamode

menu:
    main:
        - name: Tutorial
          url: /tutorial/
          weight: 15
        - name: Blog
          url: /blog/
          weight: 30
        - name: Projects
          url: /projects/
          weight: 45
        - name: Notes
          url: /notes/
          weight: 60

params:
    author: luqmannn

    ShowBreadCrumbs: false

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Luqman H.
        description: |

          Hello, welcome to my corner of the internet.

          I am Linux and open source enthusiast, a CS grad.

          I have been working in IT for some time, both during past 
          
          internships (during my diploma and degree programs) and after 
          
          completing my diploma until now. 
        imageUrl: "/images/profile.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=r9oJHpeCmHU
    mainSections:
      - tutorial

    socialIcons:
        - name: buymeacoffee
          url: "https://ko-fi.com/luqmannnh"
        - name: github
          url: "https://github.com/luqmannn/"
        
      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true